version: 0.2


phases:
  pre_build:
    commands:
      - echo pre_build
      
  build:
    commands:
      - echo build stag
  post_build:
    commands:
      - echo post_build
#artifacts:
#    files: imagedefinitions.json