version: 0.2


phases:
  pre_build:
    commands:
      - echo "Logging into Jfro...."
      - docker login tr1-docker.jfrog.io --username 6111359 --password AKCp8jQJ6BxXqVHb2hjWSMnUSocTFKHRQ3CAGFxMr7M61nAwsSNiCGBiSZSpRMkxW7B7fMHHX
      - REPOSITORY_URI=818565325759.dkr.ecr.us-east-1.amazonaws.com/a205654-tf-poc
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Build completed on `date`
      - docker images
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker images
#      - echo Writing image definitions file...
#      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
 #     - cat imagedefinitions.json 
#artifacts:
#    files: imagedefinitions.json

